-- CreateTable
CREATE TABLE "DraftAction" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "draftId" INTEGER NOT NULL,
    "teamId" INTEGER NOT NULL,
    "action" TEXT NOT NULL,
    "value" INTEGER,
    "order" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DraftAction_draftId_fkey" FOREIGN KEY ("draftId") REFERENCES "DraftTable" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "DraftAction_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
