ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "heroVideoFolderPath" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "leaderboardImagePath" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "matchCardsImagePath" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "obsWebsocketPassword" TEXT;
