#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <public-domain>" >&2
  exit 1
fi

public_domain="$1"
if [[ ! "$public_domain" =~ ^[A-Za-z0-9.-]+$ ]]; then
  echo "The domain must contain only letters, numbers, dots, or hyphens." >&2
  exit 1
fi

if [[ ! -f backend/.env ]]; then
  echo "backend/.env was not found. Run this from the project root after the VPS environment is created." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate NETWORK_JWT_SECRET." >&2
  exit 1
fi

read -r -p "Discord Application Client ID: " discord_client_id
read -r -s -p "Discord Application Client Secret (hidden): " discord_client_secret
echo
read -r -p "Discord Server (Guild) ID: " discord_guild_id

for value_name in discord_client_id discord_client_secret discord_guild_id; do
  if [[ -z "${!value_name}" ]]; then
    echo "${value_name} cannot be empty." >&2
    exit 1
  fi
done

umask 077
network_jwt_secret="$(openssl rand -hex 48)"
temporary_env="$(mktemp)"
trap 'rm -f "$temporary_env"' EXIT

grep -vE '^(DISCORD_CLIENT_ID|DISCORD_CLIENT_SECRET|DISCORD_GUILD_ID|DISCORD_REDIRECT_URI|NETWORK_FRONTEND_URL|NETWORK_JWT_SECRET|NETWORK_AUTH_PUBLIC_PATH_PREFIX)=' backend/.env > "$temporary_env" || true

printf '\n# Discord Network OAuth (generated by scripts/configure-discord-network.sh)\nDISCORD_CLIENT_ID=%s\nDISCORD_CLIENT_SECRET=%s\nDISCORD_GUILD_ID=%s\nDISCORD_REDIRECT_URI=https://%s/backend/network-auth/discord/callback\nNETWORK_FRONTEND_URL=https://%s\nNETWORK_JWT_SECRET=%s\nNETWORK_AUTH_PUBLIC_PATH_PREFIX=/backend\n' \
  "$discord_client_id" \
  "$discord_client_secret" \
  "$discord_guild_id" \
  "$public_domain" \
  "$public_domain" \
  "$network_jwt_secret" >> "$temporary_env"

mv "$temporary_env" backend/.env
trap - EXIT
chmod 600 backend/.env
unset discord_client_secret network_jwt_secret

echo "Discord network configuration saved to backend/.env."
echo "Restart the backend with: docker compose --env-file .env up -d --force-recreate backend"
