-- New draft data lives beside, but does not modify, the Prisma-owned tables.
-- Flyway remains disabled until this migration has been reviewed and a DB cutover is planned.
CREATE SCHEMA IF NOT EXISTS spring_draft;

CREATE TABLE spring_draft.draft_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INTEGER NOT NULL UNIQUE REFERENCES public."Match" ("id") ON DELETE RESTRICT,
    phase VARCHAR(32) NOT NULL,
    map_number INTEGER NOT NULL DEFAULT 1 CHECK (map_number >= 1),
    turn_team_id INTEGER REFERENCES public."Team" ("id") ON DELETE RESTRICT,
    selected_map_type VARCHAR(16),
    phase_started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    turn_deadline_at TIMESTAMPTZ,
    paused_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT draft_sessions_phase_valid CHECK (phase IN (
        'PREPARATION', 'MAP_TYPE_SELECTION', 'MAP_SELECTION', 'MAP_LOCKED',
        'HERO_BANS', 'PLAYING', 'RESULT_PENDING', 'FINISHED'
    )),
    CONSTRAINT draft_sessions_map_type_valid CHECK (
        selected_map_type IS NULL OR selected_map_type IN
        ('CONTROL', 'HYBRID', 'PAYLOAD', 'PUSH', 'FLASHPOINT')
    )
);

-- One row per played map. This is the source for picked-map history and results.
CREATE TABLE spring_draft.draft_maps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_session_id BIGINT NOT NULL REFERENCES spring_draft.draft_sessions (id) ON DELETE CASCADE,
    map_number INTEGER NOT NULL CHECK (map_number >= 1),
    map_id INTEGER NOT NULL REFERENCES public."Map" ("id") ON DELETE RESTRICT,
    map_type VARCHAR(16) NOT NULL,
    picker_team_id INTEGER NOT NULL REFERENCES public."Team" ("id") ON DELETE RESTRICT,
    selected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    play_started_at TIMESTAMPTZ,
    result_recorded_at TIMESTAMPTZ,
    winner_team_id INTEGER REFERENCES public."Team" ("id") ON DELETE RESTRICT,
    is_draw BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT draft_maps_one_per_number UNIQUE (draft_session_id, map_number),
    CONSTRAINT draft_maps_no_reuse UNIQUE (draft_session_id, map_id),
    CONSTRAINT draft_maps_type_valid CHECK (
        map_type IN ('CONTROL', 'HYBRID', 'PAYLOAD', 'PUSH', 'FLASHPOINT')
    ),
    CONSTRAINT draft_maps_result_consistent CHECK (
        (result_recorded_at IS NULL AND winner_team_id IS NULL AND NOT is_draw)
        OR
        (result_recorded_at IS NOT NULL AND ((winner_team_id IS NOT NULL) <> is_draw))
    )
);

-- A null hero_id is an explicit NO BAN. The four slots are retained as history.
CREATE TABLE spring_draft.draft_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_map_id BIGINT NOT NULL REFERENCES spring_draft.draft_maps (id) ON DELETE CASCADE,
    turn_number SMALLINT NOT NULL CHECK (turn_number BETWEEN 1 AND 4),
    team_id INTEGER NOT NULL REFERENCES public."Team" ("id") ON DELETE RESTRICT,
    hero_id INTEGER REFERENCES public."Hero" ("id") ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT draft_bans_one_per_turn UNIQUE (draft_map_id, turn_number)
);

CREATE UNIQUE INDEX draft_bans_unique_hero_per_map
    ON spring_draft.draft_bans (draft_map_id, hero_id)
    WHERE hero_id IS NOT NULL;

CREATE INDEX draft_sessions_due_turns
    ON spring_draft.draft_sessions (turn_deadline_at)
    WHERE turn_deadline_at IS NOT NULL AND paused_at IS NULL;

CREATE FUNCTION spring_draft.touch_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER draft_sessions_touch_updated_at
    BEFORE UPDATE ON spring_draft.draft_sessions
    FOR EACH ROW EXECUTE FUNCTION spring_draft.touch_updated_at();
