// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin-dashboard" | "/admin-dashboard/overwatch-content" | "/announcements" | "/assets-edition" | "/captain-dashboard" | "/dev" | "/draft" | "/draft-table/[matchId]" | "/editor-dashboard" | "/history" | "/history/season-8" | "/history/season-8/wrapped" | "/login" | "/manager-dashboard" | "/minigames" | "/minigames/jeopardy" | "/minigames/jeopardy-overview" | "/my-team" | "/news" | "/news/[articleId]" | "/overlay" | "/overlay/leaderboard/[id]" | "/overlay/map-pool-clean/[matchId]" | "/overlay/map-pool/[matchid]" | "/overlay/match-header-reversed/[matchId]" | "/overlay/match-header/[matchId]" | "/overlay/roster-a/[id]" | "/overlay/roster-b/[id]" | "/overlay/wincards/[matchId]" | "/profile" | "/schedule" | "/schedule/[matchId]" | "/season-9" | "/social-media-dashboard" | "/standings" | "/stats" | "/stats/[userId]" | "/teams" | "/teams/[teamId]" | "/wrapped"
type AppRouteHandlerRoutes = "/api/logo-square" | "/api/upload" | "/favicon.ico"
type PageRoutes = never
type LayoutRoutes = "/" | "/overlay"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin-dashboard": {}
  "/admin-dashboard/overwatch-content": {}
  "/announcements": {}
  "/api/logo-square": {}
  "/api/upload": {}
  "/assets-edition": {}
  "/captain-dashboard": {}
  "/dev": {}
  "/draft": {}
  "/draft-table/[matchId]": { "matchId": string; }
  "/editor-dashboard": {}
  "/favicon.ico": {}
  "/history": {}
  "/history/season-8": {}
  "/history/season-8/wrapped": {}
  "/login": {}
  "/manager-dashboard": {}
  "/minigames": {}
  "/minigames/jeopardy": {}
  "/minigames/jeopardy-overview": {}
  "/my-team": {}
  "/news": {}
  "/news/[articleId]": { "articleId": string; }
  "/overlay": {}
  "/overlay/leaderboard/[id]": { "id": string; }
  "/overlay/map-pool-clean/[matchId]": { "matchId": string; }
  "/overlay/map-pool/[matchid]": { "matchid": string; }
  "/overlay/match-header-reversed/[matchId]": { "matchId": string; }
  "/overlay/match-header/[matchId]": { "matchId": string; }
  "/overlay/roster-a/[id]": { "id": string; }
  "/overlay/roster-b/[id]": { "id": string; }
  "/overlay/wincards/[matchId]": { "matchId": string; }
  "/profile": {}
  "/schedule": {}
  "/schedule/[matchId]": { "matchId": string; }
  "/season-9": {}
  "/social-media-dashboard": {}
  "/standings": {}
  "/stats": {}
  "/stats/[userId]": { "userId": string; }
  "/teams": {}
  "/teams/[teamId]": { "teamId": string; }
  "/wrapped": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/overlay": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
