// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin-dashboard/overwatch-content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-dashboard/overwatch-content">> = Specific
  const handler = {} as typeof import("../../src/app/admin-dashboard/overwatch-content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assets-edition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets-edition">> = Specific
  const handler = {} as typeof import("../../src/app/assets-edition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/captain-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/captain-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/captain-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev">> = Specific
  const handler = {} as typeof import("../../src/app/dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/draft-table/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft-table/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/draft-table/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/draft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/draft">> = Specific
  const handler = {} as typeof import("../../src/app/draft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/editor-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/editor-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/history/season-8/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history/season-8">> = Specific
  const handler = {} as typeof import("../../src/app/history/season-8/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/history/season-8/wrapped/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history/season-8/wrapped">> = Specific
  const handler = {} as typeof import("../../src/app/history/season-8/wrapped/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/manager-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/manager-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minigames/jeopardy-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minigames/jeopardy-overview">> = Specific
  const handler = {} as typeof import("../../src/app/minigames/jeopardy-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minigames/jeopardy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minigames/jeopardy">> = Specific
  const handler = {} as typeof import("../../src/app/minigames/jeopardy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/minigames/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minigames">> = Specific
  const handler = {} as typeof import("../../src/app/minigames/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/my-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-team">> = Specific
  const handler = {} as typeof import("../../src/app/my-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/[articleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news/[articleId]">> = Specific
  const handler = {} as typeof import("../../src/app/news/[articleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/leaderboard/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/leaderboard/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/leaderboard/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/map-pool-clean/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/map-pool-clean/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/map-pool-clean/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/map-pool/[matchid]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/map-pool/[matchid]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/map-pool/[matchid]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/match-header-reversed/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/match-header-reversed/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/match-header-reversed/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/match-header/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/match-header/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/match-header/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/roster-a/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/roster-a/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/roster-a/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/roster-b/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/roster-b/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/roster-b/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/wincards/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overlay/wincards/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/wincards/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/schedule/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/schedule/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/season-9/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/season-9">> = Specific
  const handler = {} as typeof import("../../src/app/season-9/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/social-media-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social-media-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/social-media-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/standings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/standings">> = Specific
  const handler = {} as typeof import("../../src/app/standings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/stats/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../src/app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teams/[teamId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams/[teamId]">> = Specific
  const handler = {} as typeof import("../../src/app/teams/[teamId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams">> = Specific
  const handler = {} as typeof import("../../src/app/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wrapped/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wrapped">> = Specific
  const handler = {} as typeof import("../../src/app/wrapped/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/logo-square/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logo-square">> = Specific
  const handler = {} as typeof import("../../src/app/api/logo-square/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/favicon.ico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/favicon.ico">> = Specific
  const handler = {} as typeof import("../../src/app/favicon.ico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/overlay/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/overlay">> = Specific
  const handler = {} as typeof import("../../src/app/overlay/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
