const prisma = require("../config/prisma");

function escapeSqlString(value) {
  return String(value).replace(/'/g, "''");
}

function toSqlLiteral(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (value instanceof Date) return `'${escapeSqlString(value.toISOString())}'`;
  if (typeof value === "object") return `'${escapeSqlString(JSON.stringify(value))}'`;
  return `'${escapeSqlString(value)}'`;
}

function quoteIdent(identifier) {
  return `"${String(identifier).replace(/"/g, '""')}"`;
}

function buildInsert(table, row) {
  const columns = Object.keys(row);
  if (!columns.length) return null;
  const values = columns.map((col) => toSqlLiteral(row[col]));
  return `INSERT INTO ${quoteIdent(table)} (${columns.map(quoteIdent).join(", ")}) VALUES (${values.join(", ")});`;
}

async function generateBackupSql() {
  const [
    tournaments,
    maps,
    heroes,
    teams,
    members,
    matches,
    draftTables,
    draftActions,
    news,
    playerStats,
    allowedMapsJoin,
  ] = await Promise.all([
    prisma.tournament.findMany({ orderBy: { id: "asc" } }),
    prisma.map.findMany({ orderBy: { id: "asc" } }),
    prisma.hero.findMany({ orderBy: { id: "asc" } }),
    prisma.team.findMany({ orderBy: { id: "asc" } }),
    prisma.member.findMany({ orderBy: { id: "asc" } }),
    prisma.match.findMany({ orderBy: { id: "asc" } }),
    prisma.draftTable.findMany({ orderBy: { id: "asc" } }),
    prisma.draftAction.findMany({ orderBy: { id: "asc" } }),
    prisma.news.findMany({ orderBy: { id: "asc" } }),
    prisma.playerStat.findMany({ orderBy: { id: "asc" } }),
    prisma.$queryRawUnsafe('SELECT * FROM "_AllowedMaps" ORDER BY "A", "B"'),
  ]);

  const lines = [];
  lines.push("-- Full data backup generated by admin database tools");
  lines.push(`-- Generated at ${new Date().toISOString()}`);
  lines.push("BEGIN;");
  lines.push(
    'TRUNCATE TABLE "PlayerStat", "DraftAction", "DraftTable", "News", "Match", "Member", "Team", "Tournament", "Hero", "Map", "_AllowedMaps" RESTART IDENTITY CASCADE;'
  );

  const orderedTables = [
    ["Tournament", tournaments],
    ["Map", maps],
    ["Hero", heroes],
    ["Team", teams],
    ["Member", members],
    ["Match", matches],
    ["_AllowedMaps", allowedMapsJoin],
    ["DraftTable", draftTables],
    ["DraftAction", draftActions],
    ["News", news],
    ["PlayerStat", playerStats],
  ];

  for (const [table, rows] of orderedTables) {
    lines.push(`-- ${table}`);
    for (const row of rows) {
      const statement = buildInsert(table, row);
      if (statement) lines.push(statement);
    }
  }

  lines.push("COMMIT;");
  return `${lines.join("\n")}\n`;
}

function parseExecutableStatements(script) {
  const lines = String(script || "").split(/\r?\n/);
  const statements = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith("--")) continue;
    if (line === "BEGIN;" || line === "COMMIT;") continue;
    if (!line.endsWith(";")) {
      throw new Error("Invalid SQL format. Each statement must end with ';'.");
    }
    const upper = line.toUpperCase();
    if (!upper.startsWith("TRUNCATE TABLE") && !upper.startsWith("INSERT INTO")) {
      throw new Error("Only TRUNCATE TABLE and INSERT INTO statements are allowed.");
    }
    statements.push(line);
  }

  if (!statements.length) {
    throw new Error("No executable SQL statements found in script.");
  }

  return statements;
}

async function restoreFromBackupSql(script) {
  const statements = parseExecutableStatements(script);

  await prisma.$transaction(async (tx) => {
    for (const statement of statements) {
      await tx.$executeRawUnsafe(statement);
    }
  });

  return { executedStatements: statements.length };
}

module.exports = {
  generateBackupSql,
  restoreFromBackupSql,
};
