const prisma = require("../config/prisma");

function escapeSqlString(value) {
  return String(value).replace(/'/g, "''");
}

function toSqlLiteral(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (value instanceof Date) return `'${escapeSqlString(value.toISOString())}'`;
  if (typeof value === "object") return `'${escapeSqlString(JSON.stringify(value))}'`;
  return `'${escapeSqlString(value)}'`;
}

function quoteIdent(identifier) {
  return `"${String(identifier).replace(/"/g, '""')}"`;
}

function buildInsert(table, row) {
  const columns = Object.keys(row);
  if (!columns.length) return null;
  const values = columns.map((col) => toSqlLiteral(row[col]));
  return `INSERT INTO ${quoteIdent(table)} (${columns.map(quoteIdent).join(", ")}) VALUES (${values.join(", ")});`;
}

async function generateBackupSql() {
  const [
    tournaments,
    maps,
    heroes,
    teams,
    members,
    matches,
    draftTables,
    draftActions,
    news,
    playerStats,
    allowedMapsJoin,
  ] = await Promise.all([
    prisma.tournament.findMany({ orderBy: { id: "asc" } }),
    prisma.map.findMany({ orderBy: { id: "asc" } }),
    prisma.hero.findMany({ orderBy: { id: "asc" } }),
    prisma.team.findMany({ orderBy: { id: "asc" } }),
    prisma.member.findMany({ orderBy: { id: "asc" } }),
    prisma.match.findMany({ orderBy: { id: "asc" } }),
    prisma.draftTable.findMany({ orderBy: { id: "asc" } }),
    prisma.draftAction.findMany({ orderBy: { id: "asc" } }),
    prisma.news.findMany({ orderBy: { id: "asc" } }),
    prisma.playerStat.findMany({ orderBy: { id: "asc" } }),
    prisma.$queryRawUnsafe('SELECT * FROM "_AllowedMaps" ORDER BY "A", "B"'),
  ]);

  const lines = [];
  lines.push("-- Full data backup generated by admin database tools");
  lines.push(`-- Generated at ${new Date().toISOString()}`);
  lines.push("BEGIN;");
  lines.push(
    'TRUNCATE TABLE "PlayerStat", "DraftAction", "DraftTable", "News", "Match", "Member", "Team", "Tournament", "Hero", "Map", "_AllowedMaps" RESTART IDENTITY CASCADE;'
  );

  const orderedTables = [
    ["Tournament", tournaments],
    ["Map", maps],
    ["Hero", heroes],
    ["Team", teams],
    ["Member", members],
    ["Match", matches],
    ["_AllowedMaps", allowedMapsJoin],
    ["DraftTable", draftTables],
    ["DraftAction", draftActions],
    ["News", news],
    ["PlayerStat", playerStats],
  ];

  for (const [table, rows] of orderedTables) {
    lines.push(`-- ${table}`);
    for (const row of rows) {
      const statement = buildInsert(table, row);
      if (statement) lines.push(statement);
    }
  }

  lines.push("COMMIT;");
  return `${lines.join("\n")}\n`;
}

/**
 * Split a SQL backup script into individual executable statements.
 *
 * A previous implementation split by newline and assumed every line was a
 * full statement. That broke as soon as any exported value (News bodies,
 * rosters, JSON fields, etc.) contained a literal newline character: the
 * statement got shredded across lines and the parser rejected it with
 * "Each statement must end with ';'".
 *
 * This parser walks the script character by character and respects:
 *   - Single-quoted string literals with `''` as the SQL-standard escape for
 *     a literal quote. Newlines and semicolons inside strings are preserved
 *     and do not terminate a statement.
 *   - `-- ...` line comments (skipped entirely).
 *   - `BEGIN` / `COMMIT` control statements (ignored; the caller runs the
 *     whole batch inside a single transaction already).
 *   - Only `TRUNCATE TABLE` and `INSERT INTO` are whitelisted. Anything else
 *     is rejected to avoid executing arbitrary SQL from pasted input.
 */
function parseExecutableStatements(script) {
  const input = String(script || "");
  const statements = [];
  let current = "";
  let inString = false;
  let i = 0;

  const pushStatement = () => {
    const stmt = current.trim();
    current = "";
    if (!stmt) return;

    const upper = stmt.toUpperCase();
    if (upper === "BEGIN" || upper === "COMMIT") return;

    if (!upper.startsWith("TRUNCATE TABLE") && !upper.startsWith("INSERT INTO")) {
      throw new Error("Only TRUNCATE TABLE and INSERT INTO statements are allowed.");
    }

    statements.push(`${stmt};`);
  };

  while (i < input.length) {
    const ch = input[i];
    const next = input[i + 1];

    if (inString) {
      // Inside '...': only ' ends the string (with '' escaping a literal ').
      if (ch === "'") {
        if (next === "'") {
          current += "''";
          i += 2;
          continue;
        }
        inString = false;
      }
      current += ch;
      i += 1;
      continue;
    }

    // Line comment: skip until newline (not included in output).
    if (ch === "-" && next === "-") {
      while (i < input.length && input[i] !== "\n") i += 1;
      continue;
    }

    if (ch === "'") {
      inString = true;
      current += ch;
      i += 1;
      continue;
    }

    if (ch === ";") {
      pushStatement();
      i += 1;
      continue;
    }

    current += ch;
    i += 1;
  }

  if (inString) {
    throw new Error("Invalid SQL format. Unterminated string literal in script.");
  }

  const tail = current.trim();
  if (tail) {
    throw new Error("Invalid SQL format. Last statement is missing a ';' terminator.");
  }

  if (!statements.length) {
    throw new Error("No executable SQL statements found in script.");
  }

  return statements;
}

async function restoreFromBackupSql(script) {
  const statements = parseExecutableStatements(script);

  await prisma.$transaction(async (tx) => {
    for (const statement of statements) {
      await tx.$executeRawUnsafe(statement);
    }
  });

  return { executedStatements: statements.length };
}

module.exports = {
  generateBackupSql,
  restoreFromBackupSql,
};
